SampleProject.Web/Models/Blog/BlogItemModel.cs
using System;

namespace SampleProject.Web.Models.Blog
{
    public class BlogItemModel
    {
        public int Id { get; set; }
        public string ThumbnailUrl { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public DateTime DateCreated { get; set; }
        public int PersonId { get; set; }
        public int ViewCount { get; set; }
        public string PersonName { get; set;}
    }
}

SampleProject.Web/Models/Blog/BlogListModel.cs
using System.Collections.Generic;

namespace SampleProject.Web.Models.Blog
{
    public class BlogListModel
    {
        public List<BlogItemModel> Blog { get; set; }
    }
}

SampleProject.Web/Models/Blog/ViewBlogModel.cs
namespace SampleProject.Web.Models.Blog
{
    public class ViewBlogModel
    {
        public int Id { get; set; }
        public string ThumbnailUrl { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public int ViewCount { get; set; }
        public int PersonId { get; set; }
    }
}

SampleProject.Web/Models/Person/PeopleListModel.cs
using System.Collections.Generic;

namespace SampleProject.Web.Models.Person
{
    public class PeopleListModel
    {
        public List<PersonItemModel> People { get; set; }
    }
}

SampleProject.Web/Models/Person/PersonItemModel.cs
namespace SampleProject.Web.Models.Person
{
    public class PersonItemModel
    {
        public string Name { get; set; }

        public int Id { get; set; }

        public string ShortDescription { get; set; }

        public string Description { get; set; }

        public string ImageUrl { get; set; }

        public PersonItemModel(Common.Data.Person person)
        {
            Name = person.Name;
            Id = person.Id;
            ShortDescription = person.ShortDescription;
            Description = person.Description;
            ImageUrl = person.ImageUrl;
        }
    }
}

SampleProject.Web/Models/Person/ViewPersonModel.cs
namespace SampleProject.Web.Models.Person
{
    public class ViewPersonModel
    {
        public string Name { get; set; }
        public int Id { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
    }
}

SampleProject.Web/Controllers/BlogController.cs
using SampleProject.Common.Services;
using SampleProject.Web.Models.Blog;
using System.Linq;
using System.Web.Mvc;

namespace SampleProject.Web.Controllers
{
    public class BlogController : Controller
    {
        private readonly IBlogService _blogService = new BlogService();
        private readonly IPersonService _personService = new PersonService();

        [Route("blog")]
        public ActionResult Index()
        {
            var model = new BlogListModel();

            var blog = _blogService.GetAll();

            model.Blog = blog.Select(x => new BlogItemModel
            {
                DateCreated = x.DateCreated,
                PersonName = _personService.LoadPerson(x.PersonId)?.Name,
                Content = x.Content,
                Description = x.Description,
                Id = x.Id,
                PersonId = x.Id,
                ThumbnailUrl = x.ThumbnailUrl,
                Title = x.Title,
                ViewCount = x.ViewCount
            }).ToList();

            return View(model);
        }

        [Route("blog/{blogId:int}")]
        public ActionResult ViewBlog(int blogId)
        {
            var model = new ViewBlogModel();

            var blog = _blogService.GetBlog(blogId);

            if (blog == null)
                return HttpNotFound("Blog could not be found");

            model.Title = blog.Title;
            model.ThumbnailUrl = blog.ThumbnailUrl;
            model.Content = blog.Content;
            model.ViewCount = blog.ViewCount;
            model.Description = blog.Description;
            model.Id = blog.Id;

            return View(model);
        }
    }
}

SampleProject.Web/Controllers/HomeController.cs
using System.Web.Mvc;

namespace SampleProject.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

SampleProject.Web/Controllers/PersonController.cs
using System.Linq;
using System.Web.Mvc;
using SampleProject.Common.Services;
using SampleProject.Web.Models.Person;

namespace SampleProject.Web.Controllers
{
    public class PersonController : Controller
    {
        private readonly IPersonService _personService = new PersonService();

        [Route("people")]
        public ActionResult Index()
        {
            var model = new PeopleListModel();

            var people = _personService.GetAll();

            model.People = people.Select(x => new PersonItemModel(x)).ToList();

            return View(model);
        }

        [Route("person/{personId:int}")]
        public ActionResult ViewPerson(int personId)
        {
            var model = new ViewPersonModel();

            var person = _personService.LoadPerson(personId);

            if (person == null)
                return HttpNotFound("Person could not be found");

            model.Name = person.Name;
            model.ImageUrl = person.ImageUrl;
            model.Description = person.Description;
            model.Id = person.Id;

            return View(model);
        }
    }
}

SampleProject.Web/Views/Blog/Index.cshtml
@model SampleProject.Web.Models.Blog.BlogListModel

@{
    ViewBag.Title = "All Blog";
}

<div class="section">
    <div class="row">
        <div class="container-section">
            @foreach (var blog in Model.Blog)
            {
                <div class="grid-col">
                    <div class="blog-card">
                        <div class="row">
                            <div class="col-4">
                                <img src="@blog.ThumbnailUrl" />
                            </div>
                            <div class="col-8">
                                <div class="blog-title">@blog.Title</div>
                                @{
                                    string desc = blog.Description.Count() > 120 ? blog.Description.Substring(0, 120) + "....." : blog.Description;
                                                                <div class="blog-description">@desc @Html.ActionLink(" read more", "ViewBlog", "Blog", new { blogId = blog.Id }, null)</div>
                                }
                            <div class="row blog-count-section">
                                <div class="col-6">
                                    <div class="blog-view-count"><img class="count-img" src="~/fonts/countdown.png" />@blog.ViewCount</div>
                                </div>
                                <div class="col-6">
                                    <div class="blog-view-count"><img class="count-img" src="~/fonts/writer.png" />@blog.PersonName</div>
                                </div>
                            </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

SampleProject.Web/Views/Blog/ViewBlog.cshtml
@model SampleProject.Web.Models.Blog.ViewBlogModel
@{
    ViewBag.Title = "ViewBlog";
}

<h1>@Model.Title</h1>
<img src="@Model.ThumbnailUrl" style="float: right; margin: 0 0 20px 30px;" alt="Blog Image" />
<p>
    @Html.Raw(Model.Content.Replace("\n", "<br/>"))
</p>

SampleProject.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<br />

SampleProject.Web/Views/Person/Index.cshtml
@model SampleProject.Web.Models.Person.PeopleListModel
@{
    ViewBag.Title = "All People";
}

<h2>People</h2>

@foreach (var person in Model.People)
{
    <div>
        <h3>@person.Name</h3>
        <blockquote style="padding-left: 20px;">@person.ShortDescription @Html.ActionLink(".. view more", "ViewPerson", "Person", new { personId = person.Id }, null)</blockquote>
    </div>
}

SampleProject.Web/Views/Person/ViewPerson.cshtml
@model SampleProject.Web.Models.Person.ViewPersonModel
@{
    ViewBag.Title = "Person: " + Model.Name;
}

<h1>@Model.Name</h1>
<img src="@Model.ImageUrl" style="float: right; margin: 0 0 20px 30px;" alt="Person Image" />
<p>
    @Html.Raw(Model.Description.Replace("\n", "<br/>"))
</p>

SampleProject.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sample Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sample Application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("People", "Index", "Person")</li>
                    <li>@Html.ActionLink("Blog", "Index", "Blog")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>